version: "3.8"
services:
  api_ebook:
    image: brenolima1706/api-ebook:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:pUXSu1qNwOgl4It@postgres_prod:5432/back-ebook
      - DIRECT_URL=postgresql://postgres:pUXSu1qNwOgl4It@postgres_prod:5432/back-ebook
      - JWT_SECRET=secret
      - REDIS_PORT=6379
      - RUN_SEEDS=true
      - REDIS_HOST=redis_renovada
      - AWS_ACCESS_KEY_ID=jwedqlbin4rklmmkvqtzaqbkdncq
      - AWS_SECRET_ACCESS_KEY=j3khsrqjvyypuuuh7ywyk64uyzuphychv4s3trddjjt6f74tmxr3y
      - AWS_ACCESS_GRANT=1z7iraFeGiSz7FsS3wAe6wU9UcUtwEPfiMh1q7JN12McbJLYB41poncQKRfW5iSJ8N16Z2yaTpzBUcsU6GNyqQT5CG3Uodehuk1Ztf8SgfBnbro3De5k6oRXhcYprqcrqtsG3ujQUz54KTNekYmfkLPy3PMVT6Bn5P6RrJKzxXPVDQYiqs2ujBDBMsUp3yLGehHPJVGpiE7nbwSpEmrM7hKJPSfZqXzQq5vParg8r8VLBH95Bt2xj9tLzDD5a862Rmnq8KMxC21RY5kePMWi4YJLUAkcbCk
      - AWS_BUCKET_NAME=ebook
      - AWS_REGION=US1
      - AWS_S3_ENDPOINT=https://gateway.storjshare.io
      - SMTP_HOST=mail.jbmidia.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=noreply
      - SMTP_PASSWORD=j0M$$s5e55
      - SMTP_FROM_EMAIL=noreply@jbmidia.com
      - URL_APP=https://back.ebooksim.com
    volumes:
      - ebook_uploads:/usr/src/app/uploads
    networks:
      - externa
      - interna
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        order: stop-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

      labels:
        - "traefik.enable=true"
        - "traefik.http.services.api_ebook.loadbalancer.server.port=3332"
        - "traefik.http.services.api_ebook.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.api_ebook.service=api_ebook"
        - "traefik.http.routers.api_ebook.rule=Host(`back.ebooksim.com`)"
        - "traefik.http.routers.api_ebook.tls.certresolver=le"
        - "traefik.http.routers.api_ebook.entrypoints=websecure"
        - "traefik.http.routers.api_ebook.tls=true"

volumes:
  ebook_uploads:
    driver: local

networks:
  externa:
    external: true
  interna:
    external: true
